### ISSUE TITLE
crash after downloading druids mod and trying to start the game

### ISSUE THREAD

**Issue by Erol123449** [cleannrooster/druids#6]
added druids mod to my modpack with the other base spellengine classes 

crash report:
https://pastebin.com/JYmTDvgS

**Comment by cleannrooster** [comment]
Hi, Druids is currently not compatible with the newest version of Spell
Engine
I am in the process of updating all my mods for the refactor
It's a long process because a lot was changed under the hood
Thank you for your patience

**Comment by Erol123449** [comment]
i just realized, love the mod!
cant wait for the update!

**Comment by WesselvanGils** [comment]
Any update on this? What version of SE do we have to downgrade to as a temp fix?

**Comment by cleannrooster** [comment]
It should be fixed now - just forgot to close.
Use the latest Spell Engine.

**Comment by WesselvanGils** [comment]
I'm afraid the issue persists with spell engine v1.8.15, druids v1.0.5.0 on mc v1.21.1

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'druids' at 'com.druids.Druids'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:409)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:407)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: net/spell_engine/api/item/ItemConfig
	at knot//com.druids.config.Default.<clinit>(Default.java:16)
	at knot//com.druids.Druids.<clinit>(Druids.java:55)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:534)
	at java.base/java.lang.Class.forName(Class.java:513)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:405)
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.spell_engine.api.item.ItemConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:239)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 18 more
```

**Comment by cleannrooster** [comment]
The newest version is 1.2.1

**Comment by WesselvanGils** [comment]
Ah I didnt look on CurseForge, will you update the Modrinth page?
